language: java
sudo: false
install: true
script: mvn clean package -DskipTests=true
notifications:
  email:
    recipients: "-zely1984@gmail.com"
    on_success: never
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: j0+Hjz02G6e2/RaMFIHcezvbcwR9XqEZZtViWbFyugyCZoRcj5PFbZPiUnd4o6mbhRfm3NSCmgybifAvDNS2sUXH+RoZQYbchEvWew7YGtgsahCzmMhvVnOvJHiLY+cE+VbOinbcTNH9WvyRzen6nTvK/j4YYHCv4gehBL7Cos5oCd+4ZMab8DWAlLrDS8wJU6mABxFq5LQh0EDkwz+y0my21BplFhxZTlB2wxf3U05g9uIBxggkDbClAcUPUXrVI0w931dig2nGOGtltMIhy97ksvNDBaz+igkeUMnnyYsYVBSJvYUvOUZIIXYIouuoft1A+tis29enrLMniO7z1Hx1Buv4TGYPe7e7qdiICJzlqCDhM2VGiGuwuqRITHZv9H0uC2Z7HJItyUZmdqwSU2XO4BM7DuD7AV5gejntM4XRTKoVHCqmTuv2yO3Adxv/Il544J7LfiibLiFcqpiZB1s4zs8wLxoovCSpxYYgMEhYfiy+720UDuk86qB5C8XpCWY6Q5cRqqBWI3wXvgkzVx6RQ2C9CMuMKSH99v+B6Q/QlfEpEJonjbeugn1mRZDsny64eafR4Cc+h/IoE/+vJZSiUKiwedlDblhjxaMv1H3Mj+OvT50y6wJfdlLEz0jvMj8IhwKA22OoHTgTukJqgDgdvV3ej+WLQACppN7yaI4=
  app: obscure-tor-53327
